apiVersion: v1
kind: Pod
metadata:
  name: postgres-2
  labels:
    name: postgres
spec:
  containers:
    - name: postgres
      image: postgres:9.6.17
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: "pwd"
