apiVersion: apps/v1
kind: Deployment
metadata:
  name: codestar-deployment-adminer
  labels:
    app: adminer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        resources:
        ports:
        - containerPort: 8080